#!/usr/bin/env python3

import gns3api

api = gns3api.api()
# api = gns3api.api(host="remote")
print("GNS3 controller =", api.controller)

print()
(status, data) = api.request('GET', '/v2/version')
version = None
if status == 200:
    version = data['version']
print('GET /v2/version')
print(status, data)

print()
(status, data) = api.request('POST', '/v2/version', {"version": "0.1"})
print('POST /v2/version input={"version": "0.1"}')
print(status, data)

if version is not None:
    print()
    (status, data) = api.request('POST', '/v2/version', {"version": version})
    print('POST /v2/version input={{"version": "{}"}}'.format(version))
print(status, data)
